/// THE APP'S OWN COMMANDS ARE NOW ACL-ADJUDICATED. Before this file said so, they were not.
///
/// `docs/SECURITY_FINDINGS_2026-08-07.md` #7 closed the *delivery* path for a stored
/// `javascript:` URL reaching the LCXOS webview. The *capability* behind it was left open and
/// recorded as owed: "the six reachable `#[tauri::command]`s, including the Keychain credential
/// getter, have no app-level permission set."
///
/// This is not a guess about how Tauri behaves. It is `tauri-2.11.5/src/webview/mod.rs:1820`:
///
/// ```text
/// if (plugin_command.is_some() || has_app_acl_manifest || !is_local)
///   && invoke.acl.is_none() { reject }
/// ```
///
/// Read the three disjuncts. A *plugin* command is always adjudicated. A *remote* origin is
/// always adjudicated. An **app** command from a **local** origin is adjudicated **only if the
/// app declared an ACL manifest** — and `bare tauri_build::build()` declares none. Proof from
/// this repo rather than from the docs: the generated `gen/schemas/acl-manifests.json` carried
/// keys for `core`, `os`, `process`, `updater`, `global-shortcut`, `window-state` — and no key
/// for the app. Every `#[tauri::command]` in `lib.rs` was therefore invocable by any script
/// running in the webview, with no permission consulted, because none existed to consult.
///
/// Naming the commands below sets `has_app_acl_manifest`, which inverts the default: from here
/// on an app command is **denied unless a capability explicitly allows it**.
///
/// WHY THE LIST IS THE RATCHET, AND NOT JUST PAPERWORK. The pentest's own lesson from
/// `/v1/reviews` was that "a hand-listed set cannot fail on a member nobody thought of" — four
/// handlers were gated and a fifth was not. This list has the opposite failure mode ON PURPOSE:
/// a command added to `generate_handler!` and forgotten here is not silently reachable, it is
/// silently UNREACHABLE, and the desk breaks loudly the first time it is called. Forgetting
/// fails closed. `lib.rs`'s `every_registered_command_is_adjudicated` pins the two lists
/// together so the failure is caught at `cargo test` rather than by an operator.
///
/// `is_terminal` is listed here but DENIED in `capabilities/default.json`; see that file.
const ADJUDICATED_COMMANDS: &[&str] = &[
    "secret_set",
    "secret_get",
    "secret_delete",
    "is_terminal",
    "haptic_tap",
    "diagnostics_append",
    "update_install_precheck",
];

fn main() {
    prune_stale_autogenerated_permissions();

    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(ADJUDICATED_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}

/// Delete `permissions/autogenerated/*.toml` files for commands no longer in the list above.
///
/// FOUND BY MUTATION-TESTING THIS FILE, not by reading it. `tauri-build` writes one TOML per
/// command into that directory and then globs `permissions/autogenerated/*` — the whole
/// directory, not the list. It never removes anything. So a command deleted from
/// `ADJUDICATED_COMMANDS` leaves its `allow-…`/`deny-…` behind as a real, resolvable permission
/// on the machine that built it, and nowhere else. That divergence was observed here: with this
/// file reverted to a bare `tauri_build::build()`, `gen/schemas/acl-manifests.json` STILL
/// carried the app ACL key, rebuilt entirely from leftovers.
///
/// The consequence is a build that works on one machine and fails on a clean checkout, which is
/// the worst way to learn that a security control is stale. Pruning makes the directory
/// genuinely derived from this list.
///
/// Removal is by exact filename against the list, NOT `remove_dir_all`. `tauri-build` writes
/// these with `write_if_changed`, so in the steady state nothing is touched and the directory's
/// mtime is stable — deleting and recreating it every build would churn the mtime that
/// tauri-build's own `rerun-if-changed=permissions` watches, and rebuild the crate forever.
fn prune_stale_autogenerated_permissions() {
    let dir = std::path::Path::new("permissions/autogenerated");
    let Ok(entries) = std::fs::read_dir(dir) else {
        return; // first build, or a clean checkout: nothing to prune
    };
    let expected: Vec<String> = ADJUDICATED_COMMANDS.iter().map(|c| format!("{c}.toml")).collect();
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if !expected.iter().any(|e| e == name.as_ref()) {
            println!("cargo:warning=pruning stale autogenerated permission {name}");
            let _ = std::fs::remove_file(entry.path());
        }
    }
}
