import { createBrowserRouter } from 'react-router-dom';
import { AppLayout } from '@/components/layout';
import { Dashboard, Home, SelectOperator, OntologyExplorer, StateMap, ProductMatrix, Simulator, Settings, HoweyCalculator, ScenarioPlanner, ReadinessStack, BriefGenerator, CapitalEstimator, Roadmap, RedFlags, CompetitionAnalysis, ProductIntelligence, BdPipeline, LeadDetail, ContactWorkspace, ClaimLibrary, Handoffs, SendQueue, ExchangeGaps, DealBoard, MyTasks, MarketMap, Customer360, Notes, WinLoss, AiTools, OutreachOps, DealDesk, Integrations, BoardReport, MarketNews, ReportBuilder, KpiDashboard, AuditLog } from '@/pages';

export const router = createBrowserRouter([
  { path: '/select', element: <SelectOperator /> },
  {
    path: '/',
    element: <AppLayout />,
    children: [
      { index: true, element: <Home /> },
      { path: 'regulatory-dashboard', element: <Dashboard /> },
      { path: 'ontology', element: <OntologyExplorer /> },
      { path: 'states', element: <StateMap /> },
      { path: 'products', element: <ProductMatrix /> },
      { path: 'simulator', element: <Simulator /> },
      { path: 'howey', element: <HoweyCalculator /> },
      { path: 'scenario', element: <ScenarioPlanner /> },
      { path: 'readiness', element: <ReadinessStack /> },
      { path: 'brief-generator', element: <BriefGenerator /> },
      { path: 'capital-estimator', element: <CapitalEstimator /> },
      { path: 'roadmap', element: <Roadmap /> },
      { path: 'red-flags', element: <RedFlags /> },
      { path: 'settings', element: <Settings /> },
      { path: 'competition', element: <CompetitionAnalysis /> },
      { path: 'product-intel', element: <ProductIntelligence /> },
      { path: 'bd-pipeline', element: <BdPipeline /> },
      { path: 'bd-pipeline/:id', element: <LeadDetail /> },
      { path: 'contacts/:id', element: <ContactWorkspace /> },
      { path: 'claim-library', element: <ClaimLibrary /> },
      { path: 'outreach', element: <Handoffs /> },
      { path: 'send-queue', element: <SendQueue /> },
      { path: 'exchange-gaps', element: <ExchangeGaps /> },
      { path: 'deal-board', element: <DealBoard /> },
      { path: 'tasks', element: <MyTasks /> },
      { path: 'market-map', element: <MarketMap /> },
      { path: 'customer/:id', element: <Customer360 /> },
      { path: 'notes', element: <Notes /> },
      { path: 'notes/:projectId', element: <Notes /> },
      { path: 'win-loss', element: <WinLoss /> },
      { path: 'ai-tools', element: <AiTools /> },
      { path: 'outreach-ops', element: <OutreachOps /> },
      { path: 'deal-desk', element: <DealDesk /> },
      { path: 'integrations', element: <Integrations /> },
      { path: 'board-report', element: <BoardReport /> },
      { path: 'market-news', element: <MarketNews /> },
      { path: 'report-builder', element: <ReportBuilder /> },
      { path: 'bd-kpis', element: <KpiDashboard /> },
      { path: 'audit-log', element: <AuditLog /> },
    ],
  },
]);
